name: Build KPIs

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '17 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - run: npm run build
        env:
          CONGRESS: '119'
          CONGRESS_GOV_API_KEY: ${{ secrets.CONGRESS_GOV_API_KEY }}
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/kpis.json dist/kpis.csv || true
          git commit -m "chore: update KPIs [skip ci]" || echo "no changes"
          git push
