name: Build KPIs (Python, no API key)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '23 5 * * *'
  workflow_dispatch:

concurrency:
  group: build-kpis
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: write
    env:
      HOUSE_YEARS: "2024-2025"   # first run faster
      CONGRESSES: "118-119"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -q requests lxml beautifulsoup4 pandas python-dateutil
      - name: Build KPIs
        run: python scripts/build_kpis.py
      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/kpis.csv dist/kpis.json || true
          git commit -m "chore: update KPIs [skip ci]()
